// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
 // REQUIRES: amdgpu-registered-target
 // RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu verde -emit-llvm -o - %s | FileCheck %s --check-prefixes=VERDE
 // RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu tonga -emit-llvm -o - %s | FileCheck %s --check-prefixes=GFX8
 // RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1100 -emit-llvm -o - %s | FileCheck %s --check-prefixes=GFX11


// VERDE-LABEL: @test_amdgcn_make_buffer_rsrc(
// VERDE-NEXT:  entry:
// VERDE-NEXT:    [[RETVAL:%.*]] = alloca target("amdgpu.bufferrsrc"), align 2, addrspace(5)
// VERDE-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(8) @llvm.amdgcn.make.buffer.rsrc.p5(ptr addrspace(5) [[P:%.*]], i16 4, i32 [[NUM:%.*]], i32 [[FLAGS:%.*]])
// VERDE-NEXT:    store ptr addrspace(8) [[TMP0]], ptr addrspace(5) [[RETVAL]], align 2
// VERDE-NEXT:    [[RETVAL_0_RETVAL_0_RETVAL_0_RETVAL_0_:%.*]] = load target("amdgpu.bufferrsrc"), ptr addrspace(5) [[RETVAL]], align 2
// VERDE-NEXT:    ret target("amdgpu.bufferrsrc") [[RETVAL_0_RETVAL_0_RETVAL_0_RETVAL_0_]]
//
// GFX8-LABEL: @test_amdgcn_make_buffer_rsrc(
// GFX8-NEXT:  entry:
// GFX8-NEXT:    [[RETVAL:%.*]] = alloca target("amdgpu.bufferrsrc"), align 2, addrspace(5)
// GFX8-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(8) @llvm.amdgcn.make.buffer.rsrc.p5(ptr addrspace(5) [[P:%.*]], i16 4, i32 [[NUM:%.*]], i32 [[FLAGS:%.*]])
// GFX8-NEXT:    store ptr addrspace(8) [[TMP0]], ptr addrspace(5) [[RETVAL]], align 2
// GFX8-NEXT:    [[RETVAL_0_RETVAL_0_RETVAL_0_RETVAL_0_:%.*]] = load target("amdgpu.bufferrsrc"), ptr addrspace(5) [[RETVAL]], align 2
// GFX8-NEXT:    ret target("amdgpu.bufferrsrc") [[RETVAL_0_RETVAL_0_RETVAL_0_RETVAL_0_]]
//
// GFX11-LABEL: @test_amdgcn_make_buffer_rsrc(
// GFX11-NEXT:  entry:
// GFX11-NEXT:    [[RETVAL:%.*]] = alloca target("amdgpu.bufferrsrc"), align 2, addrspace(5)
// GFX11-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(8) @llvm.amdgcn.make.buffer.rsrc.p5(ptr addrspace(5) [[P:%.*]], i16 4, i32 [[NUM:%.*]], i32 [[FLAGS:%.*]])
// GFX11-NEXT:    store ptr addrspace(8) [[TMP0]], ptr addrspace(5) [[RETVAL]], align 2
// GFX11-NEXT:    [[RETVAL_0_RETVAL_0_RETVAL_0_RETVAL_0_:%.*]] = load target("amdgpu.bufferrsrc"), ptr addrspace(5) [[RETVAL]], align 2
// GFX11-NEXT:    ret target("amdgpu.bufferrsrc") [[RETVAL_0_RETVAL_0_RETVAL_0_RETVAL_0_]]
//
__buffer_rsrc_t test_amdgcn_make_buffer_rsrc(void *p, int num, int flags) {
  return __builtin_amdgcn_make_buffer_rsrc(p, 4, num, flags);
}
